- name: Create application secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ticketshop-secrets
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        API_USERNAME: "{{ secrets.api.username }}"
        API_PASSWORD: "{{ secrets.api.password }}"
        API_URL: "{{ secrets.api.url }}"
        AUTH_MICROSOFT_ENTRA_ID_ID: "{{ secrets.auth.id }}"
        AUTH_MICROSOFT_ENTRA_ID_SECRET: "{{ secrets.auth.secret }}"
        AUTH_MICROSOFT_ENTRA_ID_ISSUER: "{{ secrets.auth.issuer }}"
        AUTH_SECRET: "{{ secrets.secret }}"
        DFS_USERNAME: "{{ secrets.dfs.username }}"
        DFS_PASSWORD: "{{ secrets.dfs.password }}"
        SAP_URL: "{{ secrets.dfs.url }}"
        AUTH_URL: "https://{% if inventory_environment == 'test' %}test-{% endif %}ticketshop.epfl.ch"
        DATABASE_URL: "postgres://{{ secrets.database.username }}:{{ secrets.database.password }}@{{ secrets.database.host }}:5432/{{ secrets.database.name }}"

- name: Create database credentials secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ticketshop-db-credentials
        namespace: "{{ openshift_namespace }}"
        labels:
          cnpg.io/reload: "true"
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ secrets.database.username }}"
        password: "{{ secrets.database.password }}"
        database: "{{ secrets.database.name }}"

- name: Create Telegram Bot Token Secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "telegram-bot-token"
        namespace: "{{ openshift_namespace }}"
      stringData:
        BOT_TOKEN: "{{ secrets.telegram.token }}"

- name: Create S3 credentials secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: s3-credentials
        namespace: "{{ openshift_namespace }}"
      stringData:
        AWS_ACCESS_KEY: "{{ secrets.s3.accessKey }}"
        AWS_SECRET: "{{ secrets.s3.secret }}"
      type: Opaque
