apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-telegram
spec:
  receivers:
    - name: "telegram"
      telegramConfigs:
        - botToken:
            name: telegram-bot-token
            key: BOT_TOKEN
          chatID: -4878626685
          parseMode: "Markdown"
          sendResolved: true
