apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: svc0049p-ticketshop

resources:
  - ../../base

patches:
  - target:
      kind: Route
      name: ticketshop
    patch: |-
      - op: replace
        path: /spec/host
        value: ticketshop.epfl.ch
  - target:
      kind: Deployment
      name: ticketshop
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: PodDisruptionBudget
      name: ticketshop-pdb
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 1
  - target:
      kind: AlertmanagerConfig
      name: alertmanager-telegram
    patch: |-
      - op: replace
        path: /spec/receivers/0/telegramConfigs/0/chatID
        value: -4878626685
  - target:
      kind: Cluster
      name: postgres-cluster
    patch: |-
      - op: replace
        path: /spec/backup/barmanObjectStore/destinationPath
        value: "s3://svc0049-4d77b6f318ed98723ae54e86dca08cfc"
  - target:
      kind: ServiceMonitor
      name: ticketshop-probe
    patch: |-
      - op: replace
        path: /spec/endpoints/0/params/target/0
        value: https://ticketshop.epfl.ch
      - op: replace
        path: /spec/endpoints/0/relabelings/0/replacement
        value: blackbox-service.svc0049p-ticketshop.svc.cluster.local:9115
