apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ticketShop-alerts
spec:
  groups:
    - name: ticketShop-pod-alerts
      rules:
        - alert: "TicketShopPodRestartingTooOften"
          expr: >
            increase(kube_pod_container_status_restarts_total{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*"}[30m]) > 3
        - alert: "TicketShopPodMissing"
          expr: >
            absent(kube_pod_info{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*"}) == 1
        - alert: "TicketShopPodNotReady"
          expr: >
            sum by (pod) (kube_pod_status_phase{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*", phase=~"Running|Pending"}) > 0
            and
            sum by (pod) (kube_pod_status_ready{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*", condition="true"}) == 0
        - alert: "TicketShopHighMemoryUsage"
          expr: >
            (container_memory_usage_bytes{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*"} / container_spec_memory_limit_bytes{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*"}) * 100 > 85
        - alert: "TicketShopHighCPUUsage"
          expr: >
            (rate(container_cpu_usage_seconds_total{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*"}[5m]) / container_spec_cpu_quota{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*"} * container_spec_cpu_period{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*"}) * 100 > 80
        - alert: "TicketShopPodCrashLooping"
          expr: >
            rate(kube_pod_container_status_restarts_total{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*"}[15m]) > 0
        - alert: "TicketShopPodOOMKilled"
          expr: >
            (kube_pod_container_status_last_terminated_reason{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*", reason="OOMKilled"} == 1)
        - alert: "TicketShopPodImagePullError"
          expr: >
            kube_pod_container_status_waiting_reason{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*", reason=~"ImagePullBackOff|ErrImagePull"} == 1
        - alert: "TicketShopPodPending"
          expr: >
            kube_pod_status_phase{namespace="svc0049p-ticketshop", pod=~"ticketsop-.*", phase="Pending"} == 1