apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ticketshop-db
spec:
  cluster:
    name: postgres-cluster
  name: ticketshop-db
  owner: ticketshop-user
  passwordSecret:
    name: ticketshop-db-credentials
