all:
  hosts:
    openshift-prod:
      openshift_namespace: svc0049p-ticketshop
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      inventory_environment: prod
