ticketshop_keybase_dir: /keybase/team/epfl_ticketshop
ticketshop_os_namespace: "{{ inventory_hostname }}"

_docker_openshift_repository: docker-registry.default.svc:5000

cadi_base_image_oc_namespace: dinfo-cicd
_cadi_base_image_name: cadi-libs-idevfsd
_cadi_base_image_tag: latest

cadi_base_image_uri: >-
  {{ _docker_openshift_repository }}/{{ cadi_base_image_oc_namespace }}/{{ _cadi_base_image_name }}:{{ _cadi_base_image_tag }}

ticketshop_image_name: ticketshop-idevfsd
ticketshop_image_tag: preprod



dinfo_build_keybase_dir: "/keybase/team/epfl_si.build_common"

_dinfo_keybase_build_secrets: >-
  {{ lookup("file", "{{ dinfo_build_keybase_dir }}/build-secrets.yml") |
  from_yaml }}

dinfo_build_c4science_credentials: >-
  {{ _dinfo_keybase_build_secrets.c4science_clone_credentials }}

dinfo_build_cadi_libs_ssh_secret_key_path: "{{ dinfo_build_keybase_dir }}/id_rsa_c4science_idevfsd-checkouter"
dinfo_build_cadi_libs_ssh_known_hosts_cmd: "ssh-keyscan c4science.ch"
