openshift_namespace:
  dyn: >-
    {{ "ticketshop-" + inventory_environment }}
  prod: ticketshop-prod
  test: ticketshop-test

keybase_secrets: >-
  {{       _keybase_secrets_prod    if inventory_environment == "prod"
      else _keybase_secrets_preprod if inventory_environment == "test"
      else None }}
_keybase_secrets_prod: >-
    {{ lookup('file', '/keybase/team/epfl_ticketshop/secrets-prod.yml') | from_yaml }}
_keybase_secrets_preprod: >-
    {{ lookup('file', '/keybase/team/epfl_ticketshop/secrets-test.yml') | from_yaml }}

ticketshop_hostname: >-
  {{ "ticketshop.epfl.ch" if inventory_environment == "prod"
      else "ticketshop-preprod.epfl.ch" if inventory_environment == "test"
      else "localhost" }}

ticketshop_routes: >-
  {{ ["ticketshop.epfl.ch"] if inventory_environment == "prod"
      else ["test-ticketshop.epfl.ch", "ticketshop-preprod.epfl.ch"] if inventory_environment == "test"
      else "localhost" }}

ticketshop_git_branch:
  dyn: >-
    {{ "master" if inventory_environment == "prod" else "dev" }}
  fix: master

ticketshop_vhost_dir: ticketshop.epfl.ch

apache_conf_log_level: >-
  {{ "error" if inventory_environment == "prod" else "debug" }}

tequila_hostname: >-
  {{ "tequila.epfl.ch" if inventory_environment == "prod"
      else "test-tequila.epfl.ch" if inventory_environment == "test"
      else "localhost" }}

_docker_openshift_repository: docker-registry.default.svc:5000
_cadi_base_image_name: cadi-libs-idevfsd
_cadi_base_image_tag: latest
cadi_base_image_uri: >-
  {{ _docker_openshift_repository }}/dinfo-cicd/{{ _cadi_base_image_name }}:{{ _cadi_base_image_tag }}

ticketshop_image_name: ticketshop
ticketshop_image_tag:
  dyn: >-
    {{ "prod" if inventory_environment == "prod" else "preprod" }}
  prod: prod
  test: preprod

dinfo_build_keybase_dir: "/keybase/team/epfl_si.build_common"
_dinfo_keybase_build_secrets: >-
  {{ lookup("file", "{{ dinfo_build_keybase_dir }}/build-secrets.yml") |
     from_yaml }}
dinfo_build_c4science_credentials: >-
  {{ _dinfo_keybase_build_secrets.c4science_clone_credentials }}
dinfo_build_cadi_libs_ssh_secret_key_path: "{{ dinfo_build_keybase_dir }}/id_rsa_c4science_idevfsd-checkouter"
dinfo_build_cadi_libs_ssh_known_hosts_cmd: "ssh-keyscan c4science.ch"
