- name: Pull Secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: ticketshop-pull-secret
        namespace: "{{ openshift_namespace }}"
      data:
        .dockerconfigjson: "{{ pull_secret_config | to_json | b64encode }}"

- name: Service Account
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: ticketshop
        namespace: "{{ openshift_namespace }}"
      imagePullSecrets:
        - name: ticketshop-pull-secret

- name: Secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ticketshop-secrets
        namespace: '{{ openshift_namespace }}'
      type: Opaque
      data:
        api_username: '{{ keybase_secrets.api_username | b64encode }}'
        api_password: '{{ keybase_secrets.api_password | b64encode }}'
        auth_entra_id: '{{ keybase_secrets.auth_entra_id | b64encode }}'
        auth_entra_secret: '{{ keybase_secrets.auth_entra_secret | b64encode }}'
        auth_entra_issuer: '{{ keybase_secrets.auth_entra_issuer | b64encode }}'
        auth_graph_api_url: '{{ keybase_secrets.auth_graph_api_url | b64encode }}'
        auth_secret: '{{ keybase_secrets.auth_secret | b64encode }}'
        dfs_username: '{{ keybase_secrets.dfs_username | b64encode }}'
        dfs_password: '{{ keybase_secrets.dfs_password | b64encode }}'
        auth_url: '{{ keybase_secrets.auth_url | b64encode }}'

- name: Service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        labels:
          app: ticketshop
        name: ticketshop-service
        namespace: "{{ openshift_namespace }}"
      spec:
        ports:
          - name: 3000-tcp
            port: 3000
            protocol: TCP
            targetPort: 3000
        selector:
          app: ticketshop
        type: ClusterIP

- name: Routes
  kubernetes.core.k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        labels:
          app: ticketshop
          route: public
        name: "{{ ticketshop_hostname }}"
        namespace: "{{ openshift_namespace }}"
        annotations:
          haproxy.router.openshift.io/balance: roundrobin
          haproxy.router.openshift.io/disable_cookies: 'true'
      spec:
        host: "{{ ticketshop_hostname }}"
        to:
          kind: Service
          name: ticketshop-service
          weight: 100
        port:
          targetPort: 3000-tcp
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect

- name: Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ticketshop
        namespace: "{{ openshift_namespace }}"
      spec:
        replicas: 1
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 0
        selector:
          matchLabels:
            app: ticketshop
        template:
          metadata:
            labels:
              app: ticketshop
          spec:
            serviceAccountName: ticketshop
            containers:
              - image: "{{ quay_registry }}/{{ app_image_name }}:{{ app_image_tag }}"
                imagePullPolicy: Always
                name: ticketshop
                ports:
                  - containerPort: 3000
                env:
                  - name: API_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: api_username
                  - name: API_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: api_password
                  - name: AUTH_MICROSOFT_ENTRA_ID_ID
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: auth_entra_id
                  - name: AUTH_MICROSOFT_ENTRA_ID_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: auth_entra_secret
                  - name: AUTH_MICROSOFT_ENTRA_ID_ISSUER
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: auth_entra_issuer
                  - name: AUTH_MICROSOFT_GRAPH_API_URL
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: auth_graph_api_url
                  - name: AUTH_SECRET 
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: auth_secret
                  - name: DFS_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: dfs_username
                  - name: DFS_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: dfs_password
                  - name: AUTH_URL
                    valueFrom:
                      secretKeyRef:
                        name: ticketshop-secrets
                        key: auth_url
                  - name: DATABASE_URL
                    valueFrom:
                      secretKeyRef:
                          name: postgres-cluster-app
                          key: uri
                resources:
                  requests:
                    cpu: "{{ '60m' if inventory_environment == 'prod' else '10m' }}"
                    memory: "{{ '1280Mi' if inventory_environment == 'prod' else '380Mi' }}"
                  limits:
                    memory: "{{ '1280Mi' if inventory_environment == 'prod' else '380Mi' }}"
                envFrom:
                  - configMapRef:
                      name: ticketshop-conf
                livenessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 15
                  timeoutSeconds: 10
                  periodSeconds: 20
                readinessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 15
                  timeoutSeconds: 10
                  periodSeconds: 10

- name: App restart
  when: >-
    "app.restart" in ansible_run_tags
  kubernetes.core.k8s:
    state: patched
    kind: Deployment
    definition:
      metadata:
        name: ticketshop
        namespace: "{{ openshift_namespace }}"
      spec:
        template:
          metadata:
            annotations:
              last-restart: "{{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%SZ') }}"
  tags: app.restart
