- name: Deploy PostgreSQL cluster
  kubernetes.core.k8s:
      state: present
      definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          metadata:
              name: postgres-cluster
              namespace: "{{ openshift_namespace }}"
              annotations:
                  cnpg.io/skipEmptyWalArchiveCheck: "enabled"
          spec:
              instances: 2
              storage:
                  size: "5Gi"
                  storageClass: "sc-gold"
              enableSuperuserAccess: true
              resources:
                  requests:
                      cpu: "500m"
                      memory: "1Gi"
              bootstrap:
                initdb:
                  database: postgres
                  encoding: UTF8
                  localeCType: C
                  localeCollate: C
                  owner: postgres