- include_vars: ticketshop-vars.yml
  tags: always

- include_tasks:
    file: ticketshop-openshift-build-tasks.yml
    apply:
      tags:
        - ticketshop.openshift-build
  tags: always

- include_tasks:
    file: ticketshop-openshift-run-tasks.yml
    apply:
      tags:
        - ticketshop.openshift-run
  tags: always
