- name: "TicketShop - Image"
  when:
    - inventory_environment == "test"
  include_tasks:
    file: image.yml
    apply:
      tags:
        - image
  tags:
    - image
    - image.startbuild

- name: "TicketShop - App"
  include_tasks:
    file: app.yml
    apply:
      tags:
        - app
  tags: 
    - app
    - app.restart
