- name: "Build {{ ticketshop_image_name }} from cadi-base-image"
  openshift_imagestream:
    state: latest
    metadata:
      namespace: "{{ inventory_hostname }}"
      name: "{{ ticketshop_image_name }}"
    tag: "{{ ticketshop_image_tag }}"
    from:
      kind: DockerImage
      name: "{{ cadi_base_image_uri }}"
    dockerfile: >-
      {{ lookup('template', 'Dockerfile') }}
