# Create the /opt/dinfo/etc/dbs.conf and 
# /var/www/vhosts/ticketshop.epfl.ch/private/etc/access_conf secrets
- name: "ticketshop secrets"
  openshift:
    state: latest
    apiVersion: v1
    kind: Secret
    metadata:
      name: ticketshop-secrets
      namespace: '{{ openshift_namespace }}'
    type: Opaque
    data:
      dbs.conf: '{{ _dbs_conf | base64 }}'
      access_params: '{{ _access_params | base64 }}'
  vars:
    _dbs_conf: |
      {% for k, el in keybase_secrets.cadi_dbs.items() %}
      {{ k }}	{{ el.db_name }}	{{ el.db_host }}	{{ el.db_user }}	{{ el.db_pass }}
      {% endfor %}
    _access_params: |
       $sap_user = '{{ keybase_secrets.sap.user }}';
       $sap_pwd  = '{{ keybase_secrets.sap.password }}';
  tags:
    - ticketshop.dbs
    - ticketshop.secrets

- name: Service
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ticketshop-service
        namespace: "{{ openshift_namespace }}"
        labels:
          app: ticketshop
      spec:
        ports:
          - name: 8080-tcp
            port: 8080
            protocol: TCP
            targetPort: 8080
        selector:
          deploymentconfig: ticketshop
  tags:
    - ticketshop.service

- name: Routes
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "ticketshop-route-{{ item }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: ticketshop
          epfl.ch/visibility: public
      spec:
        host: "{{ item }}"
        port:
          targetPort: 8080-tcp
        tls:
          termination: edge
        to:
          kind: Service
          name: ticketshop-service
          weight: 100
        wildcardPolicy: None
  with_items: "{{ ticketshop_routes }}"
  tags:
    - ticketshop.routes

- name: Config Map
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: payonline-conf
        namespace: "{{ openshift_namespace }}"
      data:
        SITE_URL: "{{ ticketshop_hostname }}"
        TEQUILA_HOST: "{{ tequila_hostname }}"
        TICKETSHOP_APACHE_CONF: "{{ lookup('template', 'ticketshop-apache-conf.j2') }}"
        TICKETSHOP_ENVIRONMENT: "{{ inventory_environment }}"
  tags:
    - ticketshop.config
    - ticketshop.cm

- name: Promote {{ ticketshop_image_name }} image to production
  when:
    - >-
      ticketshop_build_openshift_namespace != openshift_namespace
    - >-
      "ticketshop.promote" in ansible_run_tags
  shell:
    cmd: |
      oc tag {{ ticketshop_build_openshift_namespace }}/{{ ticketshop_image_name }}:preprod {{ openshift_namespace }}/{{ ticketshop_image_name }}:{{ ticketshop_image_tag }}
  tags:
    - ticketshop.promote

# https://docs.openshift.com/container-platform/3.11/dev_guide/deployments/how_deployments_work.html#creating-a-deployment-configuration
- name: Deployment Config
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      metadata:
        name: ticketshop
        namespace: "{{ openshift_namespace }}"
        labels:
          app: ticketshop
      spec:
        replicas: 1
        selector:
          app: ticketshop
          deploymentconfig: ticketshop
        template:
          metadata:
            labels:
              app: ticketshop
              deploymentconfig: ticketshop
          spec:
            containers:
              - name: ticketshop
                image: "docker-registry.default.svc:5000/{{ openshift_namespace }}/{{ ticketshop_image_name }}:{{ ticketshop_image_tag }}"
                ports:
                  - containerPort: 8080
                    protocol: "TCP"
                imagePullPolicy: Always
                volumeMounts:
                  - name: ticketshop-apache-conf-volume
                    mountPath: /usr/local/apache2/conf/25-ticketshop.epfl.ch.conf
                    subPath: 25-ticketshop.epfl.ch.conf
                  - name: ticketshop-secrets
                    mountPath: /opt/dinfo/etc/dbs.conf
                    subPath: dbs.conf
                  - name: ticketshop-secrets
                    mountPath: "/var/www/vhosts/{{ ticketshop_vhost_dir }}/private/etc/access_params"
                    subPath: access_params
                envFrom:
                  - configMapRef:
                      name: payonline-conf
            volumes:
              - name: ticketshop-apache-conf-volume
                configMap:
                  name: payonline-conf
                  items:
                    - key: TICKETSHOP_APACHE_CONF
                      path: 25-ticketshop.epfl.ch.conf
              - name: ticketshop-secrets
                secret:
                  secretName: ticketshop-secrets
        triggers:
          - type: ImageChange
            imageChangeParams:
              automatic: true
              containerNames:
                - ticketshop
              from:
                kind: ImageStreamTag
                name: "{{ ticketshop_image_name }}:{{ ticketshop_image_tag }}"
                namespace: "{{ openshift_namespace }}"
          - type: ConfigChange
  register: _ticketshop_deploymentconfig
  tags:
    - ticketshop.dc
    - ticketshop.deploy
    - ticketshop.deploy.force
    - ticketshop.deploymentconfig

- name: "Redeploy ticketshop now"
  shell:
    cmd: "oc -n {{ openshift_namespace }} rollout latest dc/ticketshop"
  register: "_build_id"
  when: >
    _ticketshop_deploymentconfig is changed
    or
    "ticketshop.deploy.force" in ansible_run_tags
  tags:
    - ticketshop.deploy.force
