# Build a ticketshop image from cadi-base image and tag
# it. Use os-docker-registry.epfl.ch/ticketshop-test/ticketshop:preprod
# to get it.
- name: "Build {{ ticketshop_image_name }} from cadi-base-image"
  openshift_imagestream:
    state: latest
    metadata:
      namespace: "{{ openshift_namespace }}"
      name: "{{ ticketshop_image_name }}"
    source:
      dockerfile: >-
        {{ lookup('template', 'Dockerfile') }}
    tag: "{{ ticketshop_image_tag }}"
  register: _ticketshop_imagestream
  when:
    - >-
      ticketshop_build_openshift_namespace == openshift_namespace
  tags:
    - ticketshop.is
    - ticketshop.image
    - ticketshop.imagestream

- name: "Rebuild {{ ticketshop_image_name }} now"
  shell:
    cmd: "oc -n {{ openshift_namespace }} start-build --wait ticketshop"
  register: "_build_id"
  when:
    - >
      (
        _ticketshop_imagestream | default(False)
        and
        (_ticketshop_imagestream is changed)
      )
      or
      "ticketshop.build" in ansible_run_tags
    - >-
      ticketshop_build_openshift_namespace == openshift_namespace
  tags:
    - ticketshop.build

- debug:
    msg:
      - "You can follow the build logs with: "
      - "oc logs -f bc/ticketshop --version={{ _build_id.stdout | regex_search('\\d+') }} -n {{ openshift_namespace }}"
  when:
    - >
      "stdout" in _build_id
      or
      "ticketshop.build" in ansible_run_tags
    - >-
      ticketshop_build_openshift_namespace == openshift_namespace
  tags:
    - ticketshop.build
