- name: Create Docker registry pull secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ service_name }}-pull-secret"
        namespace: "{{ openshift_namespace }}"
      data:
        .dockerconfigjson: "{{ secrets.puller }}"
      type: kubernetes.io/dockerconfigjson