apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-telegram
spec:
  route:
    receiver: "telegram"
    groupWait: 20s
    groupInterval: 5m
    repeatInterval: 12h
    matchers:
      - name: sendto
        value: telegram
        matchType: "="
  receivers:
    - name: "telegram"
      telegramConfigs:
        - botToken:
            name: telegram-bot-token
            key: BOT_TOKEN
          chatID: 0
          parseMode: "Markdown"
          message: |
            {{- if .Alerts -}}
            {{- $first := index .Alerts 0 -}}
            {{- if eq $first.Status "firing" -}}
              {{- if eq $first.Labels.severity "critical" -}}
            🚨 *ALERT CRITICAL* 🚨
              {{- else if eq $first.Labels.severity "warning" -}}
            ⚠️ *ALERT WARNING* ⚠️
              {{- else if eq $first.Labels.severity "info" -}}
            ℹ️ *ALERT INFO* ℹ️
              {{- end }}
            {{- else if eq $first.Status "resolved" -}}
              {{- if eq $first.Labels.severity "critical" -}}
            ✅ *RESOLVED CRITICAL* ✅
              {{- else if eq $first.Labels.severity "warning" -}}
            ✅ *RESOLVED WARNING* ✅
              {{- else if eq $first.Labels.severity "info" -}}
            ✅ *RESOLVED INFO* ✅
              {{- end }}
            {{- end }}
            *Issue detected:* {{ $first.Annotations.summary }}
            {{- if $first.Labels.pod }}
            *Pod:* {{ $first.Labels.pod }}
            {{- end }}
            *Details:* {{ $first.Annotations.description }}
            *Incident started at:* {{ $first.StartsAt.Format "2006-01-02 15:04:05" }} UTC
            {{- end -}}
          sendResolved: true
