apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: svc0049-folder
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: grafana-xxx
  resyncPeriod: 10m0s
  title: svc0049 — Ticketshop
