apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ticketshop-probe
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  endpoints:
    - interval: 30s
      params:
        module:
          - http_2xx
        target:
          - "https://ticketshop.epfl.ch"
      path: /probe
      port: http
      scheme: http
      relabelings:
        - targetLabel: __address__
          replacement: blackbox-service.svc0049p-ticketshop.svc.cluster.local:9115
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
