apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ticketshop-url-probe
  labels:
    app: ticketshop
spec:
  jobName: ticketshop-blackbox
  module: http_2xx
  prober:
    url: blackbox-exporter:9115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
        - https://ticketshop.epfl.ch
  interval: 30s
  scrapeTimeout: 10s