apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ticketshop-probe
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  endpoints:
    - interval: 5m
      params:
        module:
          - http_2xx
        target:
          - "https://ticketshop.epfl.ch"
      path: /probe
      port: http
      relabelings:
        - action: replace
          replacement: "blackbox-exporter:9115"
          targetLabel: __address__
        - action: replace
          sourceLabels:
            - __param_target
          targetLabel: target_url
      scheme: http
